export enum EntityKind {
  Class = "ClassEntity",
  Constructor = "ConstructorEntity",
  Enum = "EnumEntity",
  EnumMember = "EnumMemberEntity",
  ExportAssignment = "ExportAssignmentEntity",
  Function = "FunctionEntity",
  Getter = "GetterEntity",
  Interface = "InterfaceEntity",
  MappedTypeMember = "MappedTypeMemberEntity",
  Member = "MemberEntity",
  Method = "MethodEntity",
  Module = "ModuleEntity",
  Namespace = "NamespaceEntity",
  Parameter = "ParameterEntity",
  Property = "PropertyEntity",
  Setter = "SetterEntity",
  Signature = "SignatureEntity",
  SourceFile = "SourceFileEntity",
  TupleMember = "TupleMemberEntity",
  TypeAlias = "TypeAliasEntity",
  TypeArgument = "TypeArgumentEntity",
  TypeParameter = "TypeParameterEntity",
  Unresolved = "UnresolvedEntity",
  Variable = "VariableEntity"
}
