name: CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"

  push:
    paths-ignore:
      - "docs/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint:ci

      - name: Typecheck
        run: npm run typecheck

      - name: Spellcheck
        run: npm run spellcheck:ci

  test:
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

    strategy:
      fail-fast: true
      matrix:
        node:
          - 18
          - 20
          - 22
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
